### ISSUE TITLE
Feature request: configurable drops

### ISSUE THREAD

**Issue by SlimeDog** [JyckoS/Blackhole#4]
Please implement a configuration option to not drop items as a result of the explosion. It's doubtful that entity drops (at least body parts like hide, meat, rabbit feet, etc, would survive the explosion (but it should be an option, so the server owner can decide).

**Comment by JyckoS** [comment]
I don't understand

**Comment by SlimeDog** [comment]
When entities are pulled into a blackhole, they die and drop whatever they drop (cows and horses and rabbits: hides; cows and pigs: raw meat; etc). The items are not pulled into the blackhole. They should be, optionally configurable.

**Comment by SlimeDog** [comment]
Closed due to dev abandonment.
