### ISSUE TITLE
Feature request: in-combat escape

### ISSUE THREAD

**Issue by SlimeDog** [JyckoS/Blackhole#9]
[CombatLogX](https://www.spigotmc.org/resources/combatlogx.31689/) (and similar plugins) tag a player as in-combat, so they cannot escape by teleportation or disconnect, etc.

Please consider using the developer API to implement this feature: that player cannot escape a blackhole by any of those means, once the pull exceeds their ability to move away.

**Comment by JyckoS** [comment]
That's creepy

**Comment by SlimeDog** [comment]
Nevertheless... Player should not be able to escape. They should die. :)

**Comment by SlimeDog** [comment]
Closed due to dev abandonment.
